### ISSUE TITLE
Android app asks Username and Password even if they are embedded in eap-config

### ISSUE THREAD

**Issue by hgot07** [geteduroam/ionic-app#119]
When an eap-config file is fed, Android app asks the user to type in Username and Password even if they are embedded in the XML file.
Windows app works well, i.e. it never asks Username and Password.
We'd like to issue eap-config files with Username/Password embedded and avoid end-users' manual operation as much as possible. One of the most values of this app is damaged by this problem.

Tested with Pixel 3 running Android 10, plus Pixel 6 running Android 12
![Screenshot_20220815-173440](https://user-images.githubusercontent.com/98217485/184603823-b77c82d7-b4d3-4a08-bb4d-e18be37a6b0c.png)
.

**Comment by hgot07** [comment]
Ah, I've found the cause.
After adding <Username>...</Username> besides the standard <UserName>...</UserName>, the app accepts the embedded username and password.

**Comment by jornane** [comment]
This is due to a bug in the current Android app. We're working on releasing a new version where this is one of the things that will be fixed. But due to Play Store rules, we can never update the app for Android 11 and below, so this workaround will be needed for quite some time to come, sadly. Maybe #117 can help.
