### ISSUE TITLE
App tries to open all file types

### ISSUE THREAD

**Issue by kenbyte** [geteduroam/ionic-app#122]
**Behavior:** Opening any file on an Android device on which geteduroam is installed gives the option to open with it, and when the file type isn't registered with any other app the device will try to open the file with geteduroam directly without asking.

**Expected:** The app should only try to open specific file types that make sense for this app.

If someone can point me in the right direction on what file types this app should actually be able to open and how to register them in the ionic framework (which I haven't worked with in the past), I can maybe attempt to fix this myself.

**Comment by jornane** [comment]
Hi @kenbyte 
This is a [known issue](90) in the current release for Android. It is already fixed in the latest version, but this latest version is not on the Play Store.

This is because the current release uses API 28, which works for configuring Wi-Fi on Android 10.
Google Play doesn't allow us to update the app without also updating the API level, which would break the app on Android 10.

If you wish, you can try a [newer release](https://play.google.com/apps/testing/app.eduroam.geteduroam) as a tester, to see if it solves your problem. We are still uncertain when we want to release this for everyone, since it will break Android 10 and there will be no way back for us.

**Comment by kenbyte** [comment]
Thank you for this information and the link to the newer release; it's unfortunate that Google Play is preventing this update from being rolled out to everyone. I will now close this issue and do wish you a pleasant Sunday.

**Comment by spaetow** [comment]
https://community.jisc.ac.uk/library/network-and-technology-service-docs/geteduroam-app - Issue 12 👍 

Jørn, if you have a side-load link for the app, please let me know and we'll update our guidance. I guess we can also link to the side-load at https://wiki.geant.org/display/H2eduroam/eduroam+Apps too :-)

**Comment by jornane** [comment]
@spaetow The APKs are published on the Releases page in this Github repository
