### ISSUE TITLE
Crash when sideloading an eap-config file

### ISSUE THREAD

**Issue by jornane** [geteduroam/ionic-app#30]
When sideloading a profile via Safari, the app opens and displays an error.

> Error: Uncaught (in promise):
> TypeError undefined is not an
> object (evaluating 'response.data')
> capacitor://localhost/build/main.js:1
> 01:46 generatorResume@[native
> code]
> fulfilled@capacitor://localhost/build/
> main.js:33:62
> onInvoke@capacitor://localhost/buil
> d/vendor.js:5085:39
> capacitor://localhost/build/polyfills.j
> s:3:10149
> capacitor://localhost/build/polyfills.j
> s:3:20245
> onInvokeTask@capacitor://localhos

It has a Back button, which brings me to a username/password prompt. The profile in question contains a client certificate and supports only EAP-TLS, so this is not correct.

**Comment by jornane** [comment]
Crash for example with the profile from https://cat.eduroam.no/download/?idp=9;profile=10;os=eap-config

**Comment by agomezmoron** [comment]
After seeing this issue the problem is realted to the app scope and how it handles files. In iOS there are 2 options:

- Open in app
- Copy in app

In geteduroam we have both but that's why that fails. When you have a file in an email for example, the only option you have is "Copy in" and that works. On the other hand, when you download a file, it's in the filesystem and you have 2 options available "Open in" and "Copy in". The Open in crases because the file is out of the app scope (and capacitor or any iOS app cannot handle file from out of its cope if that file access is not handled directly in Swift). Capacitor, as it's defined, doesn't work on that way (we detected that in a comment of a non related issue - https://github.com/ionic-team/capacitor/issues/3492 - where a member of the ionic team said "iOS don't require permissions to read files, **but can only read files inside its own sandbox, so you are probably trying to open a file outside the sandbox**" and that was the clue.

So the "Open in" option will be removed and only the "Copy in" option will be allowed. So, iOS will "copy temporary" the file into the app scope and it will be able to handle that correctly as it's handled in other scopes.
