### ISSUE TITLE
Ability to swipe back (return to previous screen)

### ISSUE THREAD

**Issue by spaetow** [geteduroam/ionic-app#38]
Consider this scenario: I am new to eduroam, I download geteduroam, I install it, I start it. I am asked for my institution. While I search for it, find it and want to select it, my bus hits a bump in the road (or I have a case of 'fat fingers') and I select the institution above mine and because I haven't paid attention, click 'Next'. It asks me for credentials. That's when I realise I've made a mistake. I can't swipe right to get back to the previous screen, nor is there a back arrow or button to take me back to the beginning. Instead I have to close the app and start again.

From a usability perspective this is not great. Could this be improved, perhaps? Call it an enhancement, if you so wish. :-)

**Comment by jornane** [comment]
I think swiping is already possible, at least on iOS. But it's not clear, so maybe a button is better?

**Comment by Cardeniosa** [comment]
We are currently working in an approach with a button (the arrow can be modified in the future):
![imagen](https://user-images.githubusercontent.com/34888098/94265796-73d85e80-ff39-11ea-9740-54711016abf2.png)

**Comment by amachadogarcia** [comment]
While we have been developing this task, we have found an issue. If the android version is equal to or greater than 29, that is, android Q, we cannot check if you already have a network configured and if it is overridable or not. The proposal we make to handle this type of situation is not to give any warning at the beginning of the application and to send it to the screen to configure a new network. In case the configuration of the new network fails, we will check if the error is due to the fact that one already exists and in that case we would show a message to the user advising him to check if he already has that network configured by him previously, and if so, delete it and go through the normal process again to set it up successfully.

**Comment by jornane** [comment]
Just don't show the "Already configured" screen anymore.

**Comment by agomezmoron** [comment]
The re-configure functionality should be removed. We will **not check any more** if eduroam was configured.

**Comment by jornane** [comment]
The feature works, but there are some things that should be better:

* The arrow is too big, the design must be cleaned up.
* There is a delay between pressing the button and it taking effect. That's okay, but there must be feedback to the user that something is happening.

![Simulator Screen Shot - iPhone SE (1st generation) - 2020-10-08 at 14 46 52](https://user-images.githubusercontent.com/767872/95460784-ab053180-0975-11eb-9f1a-15af3bf97d21.png)

**Comment by amachadogarcia** [comment]
Fixed in 4cdc69b9943c5a8969f4d37aba36f6c7b10cbce8
